### ISSUE TITLE
Where is the source code?

### ISSUE THREAD

**Issue by GoudronViande24** [3kh0/rooftop-snipers#3]
Hi, this repo says it's licenced under MIT licence, but there is no source code, only compiled binaries from Unity.

Have you just copied the game from another website and "released" it here?

**Comment by 3kh0** [comment]
You can import the binaries into unity and make your own versions of the game.

**Comment by GoudronViande24** [comment]
No you cannot, because those are compiled binaries. You have to release the source code for that.

Better explanation here: https://answers.unity.com/questions/1163739/can-you-decompile-unity-webgl-builds.html

**Comment by GoudronViande24** [comment]
By the way, the compiled binaries should not be in the master (or main) branch, but rather included as another zip file in the releases. If you want to use them with GitHub Page, you should make a separate branch for that, so you don't mix source code.

**Comment by 3kh0** [comment]
I got these game files from a cdn which has been shutdown

**Comment by GoudronViande24** [comment]
So you have not created this game, nor it is open-source...

**Comment by 3kh0** [comment]
> So you have not created this game, nor it is open-source...

yes, I just added optimize because it had memory leaks in the orginal

**Comment by GoudronViande24** [comment]
But is the original game open-source?
If not, I don't think this is really legal.

Also, GitHub repos are not made to host binaries, but for source code. Since you do not have the source code, I don't think it is completely following GitHub standards.
![image](https://user-images.githubusercontent.com/42936037/148660582-76d517ee-388e-41cf-b00e-5e75bd5caefe.png)

**Comment by 3kh0** [comment]
> But is the original game open-source? If not, I don't think this is really legal.
> 
> Also, GitHub repos are not made to host binaries, but for source code. Since you do not have the source code, I don't think it is completely following GitHub standards. ![image](https://user-images.githubusercontent.com/42936037/148660582-76d517ee-388e-41cf-b00e-5e75bd5caefe.png) Source: https://stackoverflow.com/questions/10346370/what-is-the-best-practice-of-distributing-binaries-from-a-github-project

I have contacted the maker of the game and have received no response

**Comment by GoudronViande24** [comment]
No response does not give you the right to do whatever you want.

**Comment by 3kh0** [comment]
> No response does not give you the right to do whatever you want.

So you what you are trying to say is that this repo is illegally hosted?

**Comment by GoudronViande24** [comment]
Maybe not illegal, but maybe against GitHub's TOS. But again, this issue is just about that the source code is not released, which is not really open source. Also, I'm not a lawyer or anything close to that and you should contact one, or GitHub support, if you need more advice.

**Comment by 3kh0** [comment]
> Maybe not illegal, but maybe against GitHub's TOS. But again, this issue is just about that the source code is not released, which is not really open source. Also, I'm not a lawyer or anything close to that and you should contact one, or GitHub support, if you need more advice.

ok got it
